config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :jobs do
    post '/bookings', to: 'bookings#create', as: 'quick_create'
    resources :bookings, only: %i[show] do
      resources :reviews, only: %i[show new create update edit destroy]
    end
  end
  resources :bookings, except: %i[show create] do
    patch :complete, on: :member
    patch :confirm, on: :member
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  get 'accessibility', to: 'pages#accessibility', as: :accessibility
  get 'about', to: 'pages#about', as: :about
  get 'privacy', to: 'pages#privacy', as: :privacy
  get 'statement', to: 'pages#statement', as: :statement

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  # This user is the person who created the job
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  belongs_to :category
  has_many :bookings
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < ApplicationController
  before_action :set_job, only: :show
  before_action :job_params, only: :create
  before_action :render_jobs, only: :index
  # before_action :filter_jobs?, only: :create
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    # @jobs = Job.geocoded
    @markers =
      @jobs.map do |job|
        {
          lat: job.latitude,
          long: job.longitude,
          infoWindow:
            render_to_string(partial: 'info_window', locals: { job: job })
        }
      end
  end

  def new
    @job = Job.new
  end

  def show
    @markers = []
    @markers << { lat: @job.latitude, long: @job.longitude }
  end

  def create
    @job = Job.new(job_params)
    @job.user_id = current_user.id
    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def destroy
    @job.destroy
    redirect_to jobs_path
  end

  private

  def job_params
    params.require(:job).permit(
      :title,
      :description,
      :address,
      :due_date,
      :category_id,
      :query,
      :start_time,
      :end_time,
      :longitude,
      :latitude,
      :price
    )
  end

  def set_job
    @job = Job.find(params[:id])
  end

  def filter_jobs?
    # will return true if current_user (i) has not booked job and (ii) has not posted job.
    test_array = []
    test_array << @job.user_id
    @job.bookings.each { |booking| test_array << booking.user.id }
    if user_signed_in?
      return true unless test_array.include? current_user.id
    else

    end
  end
  helper_method :filter_jobs?

  def render_jobs
    @jobs_selection =
      if params[:job].present?
        Job.geocoded.where(category_id: params[:job][:query])
      else
        Job.geocoded
      end
    @jobs =
      if current_user
        @jobs_selection.where("user_id != '#{current_user.id}'")
      else
        @jobs_selection
      end
  end
end

app/views/jobs/_info_window.html.erb
<div class="container">
  <div class="d-flex align-items-center p-2">
    <% if job.user.photo %>
      <%= image_tag job.user.photo, class: 'avatar mr-3' %>
    <% else %>
      <img
          class="avatar-large mr-3"
          src="https://avatars.abstractapi.com/v1/?api_key=6fc0780e90b04e089c32be386f5e0e24&name=<%= job.user.first_name.strip %>+<%= job.user.last_name.strip %>"
      />
    <% end %>
    <p class="text-left">Created <%= time_ago_in_words(job.created_at) %> ago by <%= job.user.first_name %>.</p>
  </div>

  <div class="text-left">
    <p><%= job.user.first_name %> needs help with <strong><%= job.category.name %></strong> on <%= job.due_date.strftime("%A, %b %d") %>.</p>
    <%= link_to job_path(job) do %>
      <button class="btn btn-outline-primary">Volunteer for this job</button>
    <% end %>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="my-3 text-center mx-auto">Find a Job in your area</h1>
  </div>
  <div class="row">
    <div id="map"
         class=" rounded shadow"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
         data-search="true">
    </div>
  </div>

  <div class="row my-3 my-5">
    <div class="col col-sm-6 mx-auto">
        <%= form_tag jobs_path, method: :get do %>
        <div class="row">
          <div class="col">
            <%= collection_select(:job, :query, Category.all, :id, :name, html_options: { class: 'input-group mb-3' }) %>
          </div>
        </div>
        <div class="row mt-2">
          <div class="col">
            <%= submit_tag "Filter by category", class: "btn btn-outline-primary" %>
            <%= link_to "Reset filter", jobs_path, class: "btn btn-outline-danger" %>
          </div>
        </div>
        </div>
        <% end %>
    </div>
  </div>

  <div class="container mb-5">
    <div class="row">
      <div class="cards-product justify-content-center">
        <% @jobs.each do |job| %>

          <div class="card-product p-3 shadow">
            <div class="mx-auto p-3 d-flex flex-column justify-content-between">
              <div class="row my-3">
                <% if job.category.name == 'Groceries' %>
                   <i class="fas fa-shopping-basket card-product-category mb-3 text-center mx-auto groceries"></i>
                <% elsif job.category.name == 'Medicine' %>
                  <i class="fas fa-briefcase-medical card-product-category mb-3 text-center mx-auto medical"></i>
                <% elsif job.category.name == 'Chores' %>
                  <i class="fas fa-tshirt card-product-category mb-3 text-center mx-auto chores"></i>
                <% else %>
                  <i class="fas fa-question-circle card-product-category mb-3 text-center mx-auto other"></i>
                <% end %>
              </div>
              <div class="row">
                <div class="col">
                  <h4 class="ml-3"><%= link_to job.title, job_path(job) %></h4>
                </div>
              </div>
              <div class="row mt-3 mx-3">
                <p class="text-secondary"><%= job.user.first_name %> needs help with <strong><%= job.category.name %></strong> on <%= job.due_date.strftime("%A, %b %d") %>. Click below to help out!</p>
              </div>
              <div class="row ml-3">
                <%= link_to job_path(job) do %>
                  <button class="btn btn-outline-primary">Volunteer for this job</button>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/jobs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 mx-auto form-login mb-5">
      <h2>Create a Job</h2>

      <%= simple_form_for [ @job ] do |f| %>
      <%=  f.input :title, input_html: { placeholder: "Give your job a catchy title." } %>
      <%=  f.input :description, input_html: { placeholder: "Give all the details about your job." } %>
      <%= f.association :category, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
      <%=  f.input :address, input_html: { placeholder: "Give your address." } %>
      <%=  f.input :due_date, as: :date, html5: true %>
      <%=  f.input :start_time, as: :integer, html5: true %>
      <%=  f.input :end_time, as: :integer, html5: true  %>
      <%= f.submit "Create a job", class: "btn btn-outline-primary" %>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container">

  <div class="row justify-content-center my-5">
    <h1 class="mb-5 text-secondary">Here are some details about this Job!</h1>
    <%# <%= image_tag "job_info.png", class: 'info-image' %>
  </div>

  <div class="row mb-5">
    <div class="col d-flex flex-column justify-content-between">
      <div class="d-flex">
        <% if @job.user.photo %>
          <%= image_tag @job.user.photo, class: 'avatar-large mr-3' %>
        <% else %>
          <img
              class="avatar-large mr-3"
              src="https://avatars.abstractapi.com/v1/?api_key=<%= ENV['ABSTRACT_API_KEY'] %>&name=<%= @job.user.first_name.strip %>+<%= @job.user.last_name.strip %>"
          />
        <% end %>
        <div>Created <%= time_ago_in_words(@job.created_at) %> ago </br>by <%= @job.user.first_name %>.</div>
      </div>
      <div>
        <h3 class="mb-4"><%= @job.title %></h3>
        <p><%= @job.description %></p>
        <p>Due: in <%= time_ago_in_words(@job.due_date) %></p>
      </div>
      <div>
        <% if filter_jobs? == true %>
          <%= link_to "Volunteer for this job", job_quick_create_path(@job), method:'post', class: "btn btn-primary mr-1" %>
        <% end %>
        <%= link_to "Back to list of jobs", jobs_path, class: "btn btn-outline-secondary" %>
      </div>
    </div>
    <div class="col">
      <div id="map" class="shadow" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>

  </div>

</div>

<% if @job.bookings.any? %>
    <div class="alert alert-warning alert-dismissable fade show">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <p>There are already others offering to volunteer for this task.</p>
      <p>You can still volunteer, but your generosity might not be necessary :)</p>
    </div>
  <% end %>