config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :jobs do
    post '/bookings', to: 'bookings#create', as: 'quick_create'
    resources :bookings, only: %i[show] do
      resources :reviews, only: %i[show new create update edit destroy]
    end
  end
  resources :bookings, except: %i[show create] do
    patch :complete, on: :member
    patch :confirm, on: :member
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  get 'accessibility', to: 'pages#accessibility', as: :accessibility
  get 'about', to: 'pages#about', as: :about
  get 'privacy', to: 'pages#privacy', as: :privacy
  get 'statement', to: 'pages#statement', as: :statement

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  # This is the user who is requesting to do the jobs
  belongs_to :user
  belongs_to :job
  has_many :reviews
  has_many_attached :invoices
  has_one :chatroom, dependent: :destroy
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: %i[show complete decline]
  before_action :any_received_booking_not_confirmed_and_not_declined?
  before_action :any_received_booking_confirmed_not_completed?
  before_action :any_received_booking_completed?
  before_action :any_requested_booking_not_confirmed?
  before_action :any_requested_booking_confirmed_not_completed?
  before_action :any_requested_booking_completed?

  def index
    # could be moved to pages view, pages controller as def dashboard
    # @received_bookings are the bookings received by current_user (as person seeking help)
    booking_array = []
    Booking.all.each do |booking|
      if booking.job.user_id == current_user.id
        # booking_array << booking if booking.job.user_id == current_user.id
        booking_array.push(booking)
      end
    end

    @received_bookings = booking_array

    @jobs = Job.where(user_id: current_user.id)
    # @requested_bookings are the bookings made by current_user (as volunteer)
    @requested_bookings = Booking.where(user_id: current_user.id)
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new
    @job = Job.find(params[:job_id])
    @booking.user_id = current_user.id
    # @booking.confirmed_datetime = @booking.job.due_date
    @booking.job_id = @job.id
    @booking.completed = false
    @booking.confirmed = false
    @booking.declined = false
    if @booking.save
      @chatroom = Chatroom.create({booking: @booking, name: @booking.job.title})
      redirect_to bookings_path
    else
      render 'jobs'
    end
  end

  def show
    # TODO: render the current user's address as a map marker
    @chatroom = @booking.chatroom
    @message = Message.new
    @markers = []
    # user's home coordinates
    @markers << { lat: @booking.user.latitude, long: @booking.user.longitude }
    # current job coordinates
    @markers << { lat: @booking.job.latitude, long: @booking.job.longitude }
  end

  def confirm
    set_booking
    @booking.confirmed = true
    @booking.save
    decline
    redirect_to bookings_path
  end

  def complete
    # @booking = Booking.find(params[:id])
    @booking.completed = true
    @booking.save
    redirect_to bookings_path
  end

  def edit
    set_booking
  end

  def update
    set_booking
    if @booking.update(booking_params)
    redirect_to bookings_path
    else
    render :edit
    end
  end


  def decline
    # get all bookings that are not the current booking and that match the current job
    @job = @booking.job
    @job.bookings.each do |booking|
      booking.declined = true unless booking.confirmed
      booking.save
    end
    # get all bookings that are not the current booking and that match the current job
    # @bookings = Booking.where(id: !@booking.id).select { |booking| booking.job == @job }
    # set declined on all those bookings == true
    # @bookings.each do |booking|
    # booking.declined = true
  end
  # TODO: create a section for this in the view, the instance of the booking will have to be passed through a link_to tag

  private

  def booking_params
    params.require(:booking).permit(invoices: [])
  end

  def set_booking
    # raise
    @booking = Booking.find(params[:id])
  end

  # this method will return true if there is at least one received_booking not confirmed and not declined
  def any_received_booking_not_confirmed_and_not_declined?
    count = 0
    index
    @received_bookings.each do |booking|
      count += 1 if !booking.confirmed && !booking.declined
    end
    true if count.positive?
  end
  helper_method :any_received_booking_not_confirmed_and_not_declined?

  # this method will return true if there is at least one received_booking confirmed and not completed
  def any_received_booking_confirmed_not_completed?
    count = 0
    index
    @received_bookings.each do |booking|
      count += 1 if booking.confirmed && !booking.completed
    end
    true if count.positive?
  end
  helper_method :any_received_booking_confirmed_not_completed?

  # this method will return true if there is at least one received_booking completed
  def any_received_booking_completed?
    count = 0
    index
    @received_bookings.each { |booking| count += 1 if booking.completed }
    true if count.positive?
  end
  helper_method :any_received_booking_completed?

  # this method will return true if there is at least one requested_booking not confirmed
  def any_requested_booking_not_confirmed?
    count = 0
    index
    @requested_bookings.each do |booking|
      count += 1 if !booking.confirmed
    end
    true if count.positive?
  end
  helper_method :any_requested_booking_not_confirmed?

  # this method will return true if there is at least one requested_booking confirmed and not completed
  def any_requested_booking_confirmed_not_completed?
    count = 0
    index
    @requested_bookings.each do |booking|
      count += 1 if booking.confirmed && !booking.completed
    end
    true if count.positive?
  end
  helper_method :any_requested_booking_confirmed_not_completed?

  # this method will return true if there is at least one requested_booking completed
  def any_requested_booking_completed?
    count = 0
    index
    @requested_bookings.each { |booking| count += 1 if booking.completed }
    true if count.positive?
  end
  helper_method :any_requested_booking_completed?
end

app/views/bookings/_chatroom.html.erb
<div class="container-chat">
<!-- <p><%= @chatroom.name %></p> -->
  <div id="messages" data-chatroom-id="<%= @chatroom.id %>">
    <% @chatroom.messages.each do |message| %>
      <div class="message-container" id="message-<%= message.id %>">
        <i class="author">
          <span><%= message.user.nickname %></span>
          <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
        </i>
        <p><%= message.content %></p>
        </div>
    <% end %>
  </div>
  <%= simple_form_for [ @chatroom, @message ], remote: true do |f| %>
    <% if current_user.id == @chatroom.booking.job.user_id %>
      <%= f.input :content, label: false, placeholder: "Message #{@chatroom.booking.user.first_name}" %>
    <% elsif current_user.id == @chatroom.booking.user_id %>
      <%= f.input :content, label: false, placeholder: "Message #{@chatroom.booking.job.user.first_name}" %>
    <% end %>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 mx-auto form-login mb-5">
    <h2>Upload receipt</h2>
      <%= simple_form_for @booking do |f| %>
        <%= f.error_notification %>
        <%= f.input :invoices, as: :file, input_html: { multiple: true } %>
        <%= f.button :submit, "Upload receipt", class: "btn-primary" %>
      <% end %>

      <%= link_to 'Cancel', bookings_path, class: "btn-outline-secondary"  %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <h1 id="header" class="my-5">Details about your booking with <%= @booking.job.user.first_name %></h1>
    <div class="row">
      <div class="col col-md-8">
      <% if @booking.user == current_user %>
      <div id="map" class="shadow" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>" data-route="true">
      </div>
    </div>
    <div class="col col-md-4 relative">
      <div class="turn-by-turn p-4">
        <div id="estimation"></div>
        <div>
          <ul id="directions" class="text-secondary"></ul>
        </div>
      </div>
    </div>
    <% else %>
    <div id="map" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <% end %>
  </div>

    <div class="row pt-4">
      <div class="col col-md-8">
        <%= render partial: "chatroom" %>
      </div>
      <div class="col col-md-4 text-secondary">
        <div class="p-3">
        <h3>Booking details:</h3>
        <p>Booking ID: <%= @booking.id %></p>
        <div class="my-3 d-flex align-items-center">
          <div>
          <% if @booking.job.user.photo %>
            <%= image_tag @booking.job.user.photo, class: 'avatar-large mr-3' %>
          <% else %>
            <img
                class="avatar-large mr-3"
                src="https://avatars.abstractapi.com/v1/?api_key=<%= ENV['ABSTRACT_API_KEY'] %>&name=<%= @booking.job.user.first_name %>+<%= @booking.job.user.last_name %>"
            />
          <% end %>
          </div>
          <div>
            <p>Created <%= time_ago_in_words(@booking.job.created_at) %> ago </br>by <%= @booking.job.user.first_name %>.</p>
          </div>
        </div>
        <div class="mb-4">
          <h5>Description:</h5>
          <p><%= @booking.job.description %></p>
        </div>
        <div>
          <h5>Status:</h5>
          <p><% if !@booking.confirmed %></p>
          <p>This booking has not been confirmed</p>
          <% elsif @booking.confirmed && !@booking.completed %>
            <p>This booking has been confirmed but not been completed</p>
          <% elsif @booking.completed %>
            This booking has been completed</p>
          <% end %>
        </div>
        <% if current_user.id == @booking.job.user_id && !@booking.confirmed %>
          <div class="row">
            <%= link_to confirm_booking_path(@booking), method: 'PATCH' do %>
              <button class="btn btn-outline-primary ml-3">Confirm this booking</button>
            <% end %>
          </div>
        <% end %>
        </div>
      </div>
    </div>

  <% # if booking is accessed by shielder : if the booking has no been confirmed, shielder can confirm %>

  <% # if booking is accessed by volunteer : if the job has been completed, volunteer can mark as complete %>

  <div class="row ml-1">
    <% if current_user.id == @booking.user_id && @booking.confirmed && !@booking.completed %>
      <%# <div class="row"> %>
        <%= link_to complete_booking_path(@booking), method: 'PATCH' do %>
        <button class="btn btn-primary mb-2">Complete job</button>
        <% end %>
      <%# </div> %>
    <% end %>
    <%= link_to "Back to bookings", bookings_path(@bookings), method:'get', class: "btn btn-outline-secondary mb-2 ml-2" %>
    <%# <%= link_to "Review your job", new_job_booking_review_path, class: "btn btn-outline-secondary mb-2" %>
    </div>
  </div>
</div>