config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :jobs do
    post '/bookings', to: 'bookings#create', as: 'quick_create'
    resources :bookings, only: %i[show] do
      resources :reviews, only: %i[show new create update edit destroy]
    end
  end
  resources :bookings, except: %i[show create] do
    patch :complete, on: :member
    patch :confirm, on: :member
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  get 'accessibility', to: 'pages#accessibility', as: :accessibility
  get 'about', to: 'pages#about', as: :about
  get 'privacy', to: 'pages#privacy', as: :privacy
  get 'statement', to: 'pages#statement', as: :statement

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="light text-black justify-content-center overflow-hidden sticky-bottom">

  <div class="row">
    <div class="col">
      <p class="text-center pt-3">
        <%= link_to "Home", root_path, class:"text-reset text-danger" %>
         | 
        <%= link_to "About us", about_path, class:"text-reset text-danger" %>
         | 
        <%= link_to "Data sharing", privacy_path, class:"text-reset text-danger" %>
         | 
        <%= link_to "Accessibility", accessibility_path, class:"text-reset text-danger" %>
         | 
        © 2020
      </p>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo_transparent.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
          <%= link_to "Jobs", jobs_path, class: "nav-link" %>
          <%= link_to "My bookings", bookings_path, class: "nav-link" %>
        <li class="nav-item">
         <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>  
        <li class="nav-item">  
          <%= link_to 'Register', new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>