config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :jobs do
    post '/bookings', to: 'bookings#create', as: 'quick_create'
    resources :bookings, only: %i[show] do
      resources :reviews, only: %i[show new create update edit destroy]
    end
  end
  resources :bookings, except: %i[show create] do
    patch :complete, on: :member
    patch :confirm, on: :member
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  get 'accessibility', to: 'pages#accessibility', as: :accessibility
  get 'about', to: 'pages#about', as: :about
  get 'privacy', to: 'pages#privacy', as: :privacy
  get 'statement', to: 'pages#statement', as: :statement

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<div class="container">

    <div class="row col-sm-12 justify-content-center">
    <h2></h2>
    </div>

    <div class="row col-sm-12 justify-content-center">
    <h2></h2>
    </div>

    <div class="row col-sm-12 justify-content-center">
    <h2>Team Local Response</h2>
    </div>

    <div class="row col-sm-12 justify-content-center">
    <h2></h2>
    </div>

    <div class="row col-sm-12 justify-content-center">
    <h2></h2>
    </div>

    <div class="row col-sm-12 justify-content-center">
    <h2></h2>
    </div>

    <div class="cards-product-team justify-content-center">

        <div class="row">
            <div class="card-product p-3 shadow rounded">
              <div class="mx-auto p-3 d-flex flex-column">
                <div class="row my-3">
                <h2> <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://avatars0.githubusercontent.com/u/61873199?s=460&u=c3fcdab175ad55d5e4e35e300ea63c472ca28192&v=4" /> Nikki Booth</h2>
                </div>
                <div class="row">
                </div>
                <div class="row mt-3 mx-3">
                 <p>I currently work at Depop. I want to change careers and enter the technical side of the industry I already work in. By the end of Le Wagon I hope to know which field I want to pursue! As of now I am open to seeing what I am most passionate about.</p>
                </div>
                <div class="row ml-3">
                </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="card-product p-3 shadow rounded">
              <div class="mx-auto p-3 d-flex flex-column">
                <div class="row my-3">
                <h2><img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://avatars0.githubusercontent.com/u/61885937?s=400&u=9828c7e543ebd4ccd9250c1c96efe9ba5f3a7833&v=4" /> Bruno Rovani</h2>
                </div>
                <div class="row">
                </div>
                <div class="row mt-3 mx-3">
                <p>I trained as an engineer and currently work in a solutions business in the financial services industry. My goal is to learn code and be able to use these skills in a role mixing finance and tech.</p>
                </div>
                <div class="row ml-3">
                </div>
              </div>
            </div>
        </div>

        <div class="row">
          <div class="card-product p-3 shadow rounded">
              <div class="mx-auto p-3 d-flex flex-column">
                <div class="row my-3">
                  <h2><img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://avatars1.githubusercontent.com/u/48836135?s=460&u=4e79f7b74f6953edebde8d971bd3e6dde652d4c4&v=4" /> Benedikt Schnatterbeck</h2>
                </div>
                <div class="row">
                </div>
                <div class="row mt-3 mx-3">
                      <p>I'm a digital marketing executive, which is where I first got exposed to HTML, CSS and Javascript. I found it so interesting that I decided I wanted to peruse a career in web development. I love technology and I'm always eager to learn more :)</p>
                </div>
                <div class="row ml-3">
                  </div>
                </div>
              </div>
        </div>

        <div class="row">
          <div class="card-product p-3 shadow rounded">
              <div class="mx-auto p-3 d-flex flex-column">
                <div class="row my-3">
                <h2> <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://avatars2.githubusercontent.com/u/62852010?s=460&u=afbb6db0ed9c50d9245dd533023cdbc6b942f8c2&v=4" /> Jayanthi Selvaraj</h2>
                </div>
                <div class="row">
                </div>
                <div class="row mt-3 mx-3">
                  <p>I work as a digital transformation consultant. I joined Le Wagon to gain hands on experience being a coder so I can better understand engineering teams, and hopefully bridge the gap between the 'product' and 'tech' divide we commonly experience in the workplace.</p>
                </div>
                <div class="row ml-3">
                  </div>
                </div>
              </div>
        </div>

     </div>

    <div class="row col-sm-12 justify-content-center">
    <h2></h2>
    </div>

</div>

app/views/pages/accessibility.html.erb
<div class="container">

<div class="row">
  <h3> Accessibility </h3>
  <p> Local response is committed to providing a website that is accessible and easy to use for the widest range of visitors possible, regardless of disability or impairment. We believe that this is an ongoing process and are constantly seeking to improve in this area.
  The site has been designed to adhere to best practice by following W3C standards. Pages have been built to comply with a minimum standard of WCAG 2.0 single 'A' guidelines. Wherever possible we aim to extend this to 'AA' and 'AAA' compliance.
  There are a number of steps we have taken to address accessibility needs that are detailed below: </p>
</div>

<div class="row">
  <h3> Layout </h3>
  <p> The site uses Cascading Style Sheets (CSS) to control all presentation and layout so that content is well structured and easily accessible via assistive devices.</p>
</div>

<div class="row">
  <h3> Further information </h3>
<p> More information on how to make your browsing experience easier is available for the BBC's My Web My Way website. This includes advice and help for those who may benefit from making changes to their browser, operating system or computer to be able to view the web in a more accessible way.</P>
</div>

</div>

app/views/pages/home.html.erb
<div class="jumbotron" style="background-image: url(/assets/images/living-room-scene.png)">
  <div class="row">
  <div class="col-md-3">
    <%= image_tag 'logo_transparent.png', class: "w-100" %>
  </div>
  <div class="col-md-9 flex-column">
    <h1 class="text-secondary"><b>Empowering individuals to help one another during times of crisis.</b></h1>
    <hr class="my-4">
    <%= link_to "I want to volunteer", jobs_path, class: "btn btn-primary btn-lg"%>
    <%= link_to "Get help today", new_job_path, class: "btn btn-outline-secondary btn-lg" %>
  </div>
  </div>
</div>

<div class="container">
  <h2 class="text-secondary text-center mt-5">No-one should feel alone or struggle with basic tasks. </h1>
  <div class="row align-items-center">
    <div class="col-md-6">
      <%= image_tag "food.png", class: "w-70 p-5" %>
    </div>
    <div class= "text-secondary col-md-6">
      <h5>Let’s fix the growing care gap by helping with the simple stuff. Together we can <b style="color: #4F62AE;">renew and regenerate our communities </b> to create a better Britain from the crisis. We are committed to helping the <b style="color: #4F62AE;">thousands</b> of people that are the <b style="color: #4F62AE;"> heart of our communities</b> </h5>
    </div>
  </div>

<div class="container">
  <h2 class="text-secondary text-center mt-5">A new generation of volunteers.</h2>
  <div class="row align-items-center">
    <div class="class= text-secondary col-md-6">
      <h5>We aim to make volunteering <b style="color: #4F62AE;">simple</b>. On your terms and to <b style="color: #4F62AE;">fit your schedule</b>.
      We’ll carry out <b style="color: #4F62AE;">safety</b> checks for you which are valid for a year and show you volunteering opportunities that are nearby.</h5>
    </div>
    <div class="col-md-6">
      <%= image_tag "navigation.png", class: "w-100 p-5" %>
    </div>
  </div>

<div class="container mb-5">
  <h2 class="text-secondary text-center mt-5"> Increase productivity during lockdown by helping people in a way that matters.</h1>
  <div class="row align-items-center">
  <div class="col-md-6">
      <%= image_tag "reminder_note.png", class: "w-100" %>
    </div>
    <div class="text-secondary col-md-6">
      <h5>Increase your <b style="color: #4F62AE;">time management skills</b>. It takes effort to rearrange schedules from leisure and family activities to make time for others. Volunteering will help you become flexible and <b style="color: #4F62AE;">learn to prioritize your time and what you value.</b></h5>
    </div>
  </div>


</div>

app/views/pages/privacy.html.erb
<div class="container">

<div class="row">
    <h3> Data sharing </h3>
    <p> Please be assured that you will not receive offers from other companies or organisations as a result of giving your details to us.
    We may need to share limited information with our service providers who help us to prepare and send you our communications or process your donations and other responses. However, we do not allow these organisations to use your data for their own purposes and take care to ensure that they keep your data secure, and delete it when it is no longer needed.</p>
</div>

</div>

app/views/pages/statement.html.erb
<div class="container">

<div class="row">
    <h3> Modern Slavery Statement </h3>
    <p> The UK's Modern Slavery Act 2015 requires organisations with an annual turnover of at least £36m to make a public statement on steps they are taking to identify and prevent modern slavery in their operations and supply chains.</p>
</div>

<div class="row">
    <h3> Feminist Principles </h3>
    <p> Local Response believes in ending sexism and that women should be free of political, social, and economic oppression and exploitation.</p>
</div>

</div>